### ISSUE TITLE
Project plan

### ISSUE THREAD

**Issue by tudorcoroian17** [OanaJimborean/Rubberizing_Minecraft#1]
Draw a Gantt Chart to showcase the initial project plan. It should contain:

- Tasks (what you plan to implement) -> features
- Time estimations (day-granularity)
- Timeline (in months) -> from October to May

**Comment by OanaJimborean** [comment]
[ProjectPlan_JimboreanOana.xlsx](https://github.com/OanaJimborean/Rubberizing_Minecraft/files/13438111/ProjectPlan_JimboreanOana.xlsx)

**Comment by tudorcoroian17** [comment]
Closing issue as completed
