### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by tudorcoroian17** [OanaJimborean/Rubberizing_Minecraft#2]
Design the initial model of the application (mod). It should contain classes of new items that you plan to add (or items that instantiate the `Item` class), as well as blocks (and block entities, if applicable), structures. This should be (roughly) an UML diagram.
Additionally, feel free to draw other diagrams that you need, such as:

- use case diagrams
- system diagrams

**Comment by OanaJimborean** [comment]
[Uploading Presentation1_JimboreanOana.pptx…]()

**Comment by tudorcoroian17** [comment]
Please attach .ppt and close this issue 😄

**Comment by OanaJimborean** [comment]
[Presentation1_JimboreanOana.pptx](https://github.com/OanaJimborean/Rubberizing_Minecraft/files/13672675/Presentation1_JimboreanOana.pptx)
